version: '3.4'

services:

  # a fully loaded development environment to test new code
  devbox: &devbox
    build:
      dockerfile: ./docker/devbox.dockerfile
      context: .
    image: "hyper-bump-it-devbox"
    volumes:
      - ./:/app

  # run all the tests and linting locally
  # - black & isort will format code to address issues
  test:
    <<: *devbox
    command: ["hatch", "run", "check"]

  # generate and serve the project documentation locally
  mkdocs: &mkdocs
    <<: *devbox
    entrypoint: "mkdocs"
    ports:
      - "8000:8000"
    command: ["hatch", "run", "docs:serve"]

  mike:
    <<: *mkdocs
    entrypoint: ["hatch", "run", "docs:mike"]

