name: Publish Release

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.12"

on:
  release:
    types: [published]

jobs:
  update_docs_for_version_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Initialize Hatch
        uses: ./.github/actions/initialize-hatch
        with:
          environment-name: "docs"
          activate: "true"

      - name: Push documentation changes
        uses: ./.github/actions/publish-docs-with-mike
        with:
          new_version: true

  build-distributions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build wheel
        uses: ./.github/actions/build-dist

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: distributions
          path: ./dist

  publish-to-pypi:
    runs-on: ubuntu-latest
    environment: "Upload Release"
    permissions:
      id-token: write
    needs: ["build-distributions"]
    steps:
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
            name: distributions
            path: ./dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
